#!/bin/sh
# vim:ft=sh:ts=2:sw=2:fdm=marker

xrandr --output HDMI1 --mode 1920x1080 --primary --pos 0x840 --rotate normal --output LVDS1 --off --output VIRTUAL1 --off --output DP1 --off --output VGA1 --mode 1920x1200 --pos 1920x0 --rotate left

