primary_monitor = "eDP-1"
dpi = 140
bar_height = 28
resolution_height = 1080
resolution_width = 1920
rofi_width = $$(( $(resolution_width) * 20/100 ))
rofi_height = $$(( $(resolution_height) - $(bar_height) ))
font = "Iosevka 18px"
dunst_width = (0, 300)
dunst_height = 600
dunst_offset = 0x$(bar_height)
