#!/bin/sh
# vim:ft=sh:ts=2:sw=2:fdm=marker

lxqt-policykit-agent &

#xrandr --output HDMI1 --mode 1920x1080 --primary --pos 0x840 --rotate normal --output LVDS1 --off --output VIRTUAL1 --off --output DP1 --off --output VGA1 --mode 1920x1200 --pos 1920x0 --rotate left

xrandr --output HDMI1 --primary --mode 1920x1080 --pos 1920x0 --rotate normal --output LVDS1 --off --output VIRTUAL1 --off --output DP1 --off --output VGA1 --mode 1920x1080 --pos 0x0 --rotate normal


